# Generated by Django 2.2.8 on 2019-12-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Variable",
            fields=[
                (
                    "name",
                    models.SlugField(max_length=64, primary_key=True, serialize=False),
                ),
                ("value", models.BinaryField()),
            ],
            options={"ordering": ("name",),},
        ),
    ]
