# Generated by Django 2.2.8 on 2019-12-14 22:05

from django.db import migrations

import persistent_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ("persistent_settings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="variable", name="value_binary",),
        migrations.AddField(
            model_name="variable",
            name="value",
            field=persistent_settings.models._PickleField(null=True),
        ),
    ]
