# Generated by Django 2.2.8 on 2019-12-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persistent_settings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="variable", old_name="value", new_name="value_binary",
        ),
    ]
