# Generated by Django 2.2.8 on 2019-12-26 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("persistent_settings", "0002_auto_20191214_2205"),
    ]

    operations = [
        migrations.AddField(
            model_name="variable",
            name="user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variables",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
