# Generated by Django 2.2.8 on 2019-12-26 22:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("persistent_settings", "0003_variable_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="variable", unique_together={("id", "user")},
        ),
    ]
