# Generated by Django 2.2.8 on 2019-12-27 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("persistent_settings", "0004_auto_20191226_2223"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variable", name="name", field=models.SlugField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name="variable", unique_together={("name", "user")},
        ),
    ]
