name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6, 3.7]
        django-version: [2.0, 2.1, 2.2]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # ref: https://stackoverflow.com/a/54053100/2926992
        cat requirements.txt | sed -e '/^\s*#.*$/d' -e '/^\s*$/d' | xargs -n 1 pip install
        cat dev.requirements.txt | sed -e '/^\s*#.*$/d' -e '/^\s*$/d' | xargs -n 1 pip install
        pip install django==${{ matrix.django-version }} --upgrade
    - name: Check Linting
      if: ${{ matrix.python-version }} == '3.7'
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --exclude .venv
    - name: Check Formatting
      if: ${{ matrix.python-version }} == '3.7'
      run: |
        black . --check
    - name: Run Tests
      run: |
        pytest
